[package]
name = "sqlxinsert"
version = "0.2.0"
authors = ["Filip Bucek <fbucek@invloop.cz>"]
edition = "2018"
license = "MIT"
description = "Sqlx derive macro for simpler inserts"
repository = "https://github.com/fbucek/sqlxinsert"
readme = "README.md"
exclude = [".github/*"]

[lib]
proc-macro = true

[dependencies]
eyre = "0.6"
quote = "1.0"
syn = "1.0"
async-trait = "0.1"
sqlx = { version = "0.4", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "postgres"] }

[dev-dependencies]
tokio = { version = "0.2", features= ["rt-threaded",  "macros"] }
sqlx = { version = "0.4", default-features = false, features = ["runtime-tokio-rustls", "macros", "sqlite", "postgres"] }

